services:
  ewm-db:
    image: postgres:16.1
    container_name: ewm-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=ewmuser
      - POSTGRES_PASSWORD=ewmpass
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ewmuser -d main_service_db" ]
      interval: 10s
      timeout: 5s
      retries: 5