server:
  port: 0

spring:
  datasource:
    driverClassName: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5432/request_service_db"
    username: "ewmuser"
    password: "ewmpass"
  jpa:
    hibernate:
      ddl-auto: none # Отключение автоматического изменения структуры таблиц
    properties:
      hibernate:
        format_sql: true # Форматирует SQL-запросы для удобства чтения
        show_sql: false # Показывает SQL-запросы в логах
  data:
    web:
      pageable:
        serialization-mode: via_dto
  sql:
    init:
      mode: always
logging:
  level:
    root: INFO
    ru.practicum.ewm: DEBUG
    org.zalando.logbook: TRACE

stats-server:
  url: http://localhost:9090

grpc:
  server:
    port: -1
  client:
    collector:
      address: discovery:///collector
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

    analyzer:
      address: discovery:///analyzer
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
