server:
  port: 8080

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway,health,info

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: request_service_route
          uri: lb://request-service
          predicates:
            - Path=/users/*/requests/**, /users/*/events/*/requests, /int/requests/**

        - id: main_service_route
          uri: lb://main-service
          predicates:
            - Path=/int/events/**, /users/*/events/**, /admin/categories/**, /admin/compilations/**, /compilations/**, /events/**, /categories/**, /admin/events/**

        - id: stats_service_route
          uri: lb://stats-service
          predicates:
            - Path=/hit/**, /stats/**

        - id: user_service_route
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**, /int/admin/users/**

