server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: main_service_route
          uri: lb://main-service
          predicates:
            - Path=/admin/categories/**, /compilations/**,  /events/**, /categories/**, /users/**

        - id: stats_service_route
          uri: lb://stats-service
          predicates:
            - Path=/hit/**, /stats/**

        - id: user_service_route
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**, /int/admin/users/**
